default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: random_images_development

test:
  <<: *default
  database: random_images_test
production:
  <<: *default
  database: random_images_production
  username: random_images
  password: <%= ENV['RANDOM_IMAGES_DATABASE_PASSWORD'] %>
